#!/bin/bash
# (1) prompt user, and read command line argument
# read -p "Which environment? [Test,Dev,Prod]: " answer

ANSWER=$1
# (2) handle the command line argument we were given
while true
do
  case $ANSWER in
   [dD]* )
     echo "Changing to Dev-environment..."
     cp app/env-configs/dev.json app/settings.json
#             <key>CFBundleDisplayName</key>
#             <string>Hearing Test</string>
#Change it to
#        <key>CFBundleDisplayName</key>
#        <string>Hearing Test Dev</string>
#     sed -i 's#<string>Hearing Test</string>#<string>Hearing Test Dev</string>#' ios/madapp/Info.plist

     echo "Changed to Dev-environment"
     break;;
   [tT]* )
     echo "Changing to Test-environment..."
     cp app/env-configs/test.json app/settings.json
     echo "Changed to Test-environment"
     break;;
   [qQ]* )
     echo "Changing to QA-environment..."
     cp app/env-configs/qa.json app/settings.json
     echo "Changed to QA-environment"
     break;;
      [pP]* )
     echo "Changing to Prod-environment..."
     cp app/env-configs/prod.json app/settings.json
     echo "Changed to Prod-environment"
     break;;
   * )     echo "Please specify which environment you want. [Test, Dev, Prod, QA]"; break ;;
  esac
done
